name: tech_task
description: A new Flutter project.

version: 1.0.0+1


environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 5.3.2
  flutter_bloc:
  retrofit: '>=4.0.0 <5.0.0'
  get_it: ^7.2.0
  logger: any
  pretty_dio_logger: ^1.1.1
  equatable: ^2.0.5
  json_annotation: ^4.5.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable:



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true